### ISSUE TITLE
npm ERR! 404 Not Found: @chartiq/finsemble-electron-adapter@3.8.*

### ISSUE THREAD

**Issue by vivian-farrell** [ChartIQ/finsemble-seed#355]
Since yesterday, this error has been introduced. Occurs when running npm install.

npm ERR! code E404
npm ERR! 404 Not Found: @chartiq/finsemble-electron-adapter@3.8.*

**Comment by JimmyStevens** [comment]
The error has been resolved. Thank you for reporting @vivian-farrell !
