### ISSUE TITLE
OSX - npm install fails on finsemble-electron-adapter sub dependency eslint-config-airbnb

### ISSUE THREAD

**Issue by vivian-farrell** [ChartIQ/finsemble-seed#358]
The error appears to be due to eslint-config-airbnb's usage of in-publish and eslint-find-rules. On a Mac, we see permission denied when attempting to run these scripts.

I have tried sudo, didn't make a difference. If I get time, I'll look into it further (unless someone fixes before me).

> eslint-config-airbnb@17.1.0 prepublish /Users/vivian.farrell/dev/finsemble/finsemble-seed/node_modules/@chartiq/finsemble-electron-adapter/node_modules/@chartiq/eslint-config-chartiq-base/packages/eslint-config-airbnb
> (in-install || eslint-find-rules --unused) && (not-in-publish || npm test) && safe-publish-latest

sh: /Users/vivian.farrell/dev/finsemble/finsemble-seed/node_modules/@chartiq/finsemble-electron-adapter/node_modules/@chartiq/eslint-config-chartiq-base/packages/eslint-config-airbnb/node_modules/.bin/in-install: Permission denied
sh: /Users/vivian.farrell/dev/finsemble/finsemble-seed/node_modules/@chartiq/finsemble-electron-adapter/node_modules/@chartiq/eslint-config-chartiq-base/packages/eslint-config-airbnb/node_modules/.bin/eslint-find-rules: Permission denied

**Comment by NinjaManatee** [comment]
We are looking into the issue now. The issue appears to be in the finsemble-electron-adapter package where _finsemble-electron-adapter/node_modules/@chartiq/eslint-config-chartiq-base/packages/eslint-config-airbnb/node_modules/.bin_ does not exist. We are working to resolve this issue. 

The electron adapter does not currently work on any OS other than Windows, so you will not be able to develop Finsemble on Mac or Linux using Electron.

**Comment by sean-ciq** [comment]
@vivian-farrell , following-up on this issue. OSX support will be available in our upcoming 5.1 release later this fall.
