### ISSUE TITLE
Finsemble 4.1.0 not working when hosted

### ISSUE THREAD

**Issue by pratikgcet** [ChartIQ/finsemble-seed#650]
The latest version doesnt launch when hosted on a server. It works fine when run locally.
Manifest below
{
	"devtools_port": 9090,
	"startup_app": {
		"name": "ChartIQ Local",
		"url": "http://qnn:3375/finsemble/services/systemManager/systemManager.html",
		"uuid": "Finsemble",
		"requireHandshake": true,
		"applicationIcon": "http://qnn:3375/assets/img/Finsemble_Taskbar_Icon.png",
		"defaultTop": 75,
		"defaultLeft": 200,
		"defaultHeight": 950,
		"defaultWidth": 700,
		"showTaskbarIcon": true,
		"autoShow": false,
		"frame": true,
		"resizable": true,
		"maximizable": false,
		"delay_connection": true,
		"contextMenu": true,
		"cornerRounding": {
			"width": 4,
			"height": 4
		},
		"alwaysOnTop": false
	},
	"splashScreenImage": "http://qnn:3375/assets/img/pic-icon.png",
	"runtime": {
		"arguments": "--noerrdialogs  --v=4 --no-sandbox  --framestrategy=frames --winhttp-proxy-resolver",
		"version": "9.61.36.36",
		"//": "Add these arguments when diagnosing issues",
		"--enable-crash-reporting": "Adding this flag will enable crash reporting to openfin, which has caused memory leaks in some versions.",
		"--diagnostics": "Adding this to the runtimeArguments activates verbose logging and crash reporting.",
		"--disable-gpu": "This flag disables hardware acceleration. Try this if 'Blank Screen' issues are reported (sometimes on virtual desktops)",
		"--winhttp-proxy-resolver": "Chromium v56 contains a bug that in some environments can create a memory leak. The bug is related to the way Chromium handles PAC files."
	},
	"shortcut": {
		"company": "CHartIq",
		"description": "ChartIQ Local",
		"icon": "http://qnn:3375/assets/img/picss-icon.ico",
		"name": "ChartIQ - LOCAL",
		"target": [
			"desktop",
			"start-menu"
		],
		"force": false,
		"startMenuRootFolder": "ChartIQ Local"
	},
	"dialogSettings": {
		"logo": "http://qnn:3375/assets/img/ciq-banner-100x25.png",
		"bgColor": 4280109424,
		"textColor": 4293521652,
		"progressBarBgColor": 4294967295,
		"progressBarFillColor": 4282684881,
		"progressBarBorderColor": 4293521652
	},
	"supportInformation": {
		"company": "ChartIQ",
		"product": "Finsemble Local Demo",
		"email": "finsemble@chartiq.com"
	},
	"fileName": "ChartIQ-local-installer",
	"appAssets": [{
		"src": "https://assets.finsemble.com/assimilation/assimilation_4.0.0.0.zip",
		"version": "4.0.0",
		"alias": "assimilation",
		"target": "AssimilationMain.exe"
	}],
	"finsemble": {
		"applicationRoot": "http://qnn:3375",
		"moduleRoot": "$applicationRoot/finsemble",
		"servicesRoot": "$applicationRoot/finsemble/services",
		"notificationURL": "$applicationRoot/components/notification/notification.html",
		"bootConfig": {
			"onErrorMakeSystemManagerVisible": true,
			"defaults": {
				"startServiceTimeout": 10000,
				"startComponentTimeout": 15000,
				"startTaskTimeout": 10000
			}
		},
		"importConfig": [
			"$applicationRoot/configs/application/config.json"
		],
		"router": {
			"crossDomainTransport": "IPCBus",
			"transportSettings": {
				"FinsembleTransport": {
					"serverAddress": "ws://127.0.0.1:3376"
				}
			}
		}
	}
}

**Comment by kriswest** [comment]
Hi @pratikgcet, @WatsonCIQ will be in touch with you through the support portal about this. We've got examples of 4.1 working fine with a hosted dist folder and they do not require any changes over 4.0 to work as far as we are aware.

We can be available to jump on a call with you and review the issue now.
