### ISSUE TITLE
global CSS leak in _toolbar.css

### ISSUE THREAD

**Issue by DimitarChristoff** [ChartIQ/finsemble-seed#716]
https://github.com/ChartIQ/finsemble-seed/blob/4.4.3/assets/css/_toolbar.css#L64

this defines `span > svg { }` which offsets any such svg icons on the page and interferes with the hosted apps. I know it's deprecated in 5.x but there are still projects tracking 4.x

**Comment by sgd2z** [comment]
Hi @DimitarChristoff, this will be resolved in Finsemble 5.1.0.
