### ISSUE TITLE
window.open override causes 404 for font resources

### ISSUE THREAD

**Issue by draperj** [ChartIQ/finsemble-seed#719]
In file nativeOverrides.js > window.open when an underlying application calls window.open within a Finsemble window, the new window is not able to properly load finsemble window font assests:
![image](https://user-images.githubusercontent.com/12603322/97719435-74ff2d00-1a9d-11eb-9467-ca341598e81e.png)

**Comment by sean-ciq** [comment]
@draperj thank you for reporting this issue. This will be escalated to our internal development teams to resolve.

**Comment by kriswest** [comment]
Resolved many moons ago
