### ISSUE TITLE
fdc3.open should throw AppNotFound when the given app is not in the directory

### ISSUE THREAD

**Issue by ColinEberhardt** [ChartIQ/finsemble-seed#766]
See: https://github.com/ScottLogic/FDC3-conformance-framework/issues/26

The failure occurs because our fdc3.open tests relies on the desktop agent throwing `AppNotFound` for the given appId. Finsemble throws `ErrorOnLaunch` instead.

Other than that, great job - 14/15 tests pass 👍

**Comment by kriswest** [comment]
Thanks @ColinEberhardt I'll pass that on to our team to resolve.

**Comment by kriswest** [comment]
I'm told this was fixed last week by @mhmcclung and has just been awaiting release!
