### ISSUE TITLE
The fdc3.open function returns a 'error' string rather than an error

### ISSUE THREAD

**Issue by ColinEberhardt** [ChartIQ/finsemble-seed#773]
If I execute the following:

~~~
fdc3.open("NoAppId").catch(e => console.log("type of thrown object", typeof e));
~~~

The following is logged:

~~~
type of thrown object string
~~~

However, the API indicates that:

> If opening errors, it returns an Error with a string from the [OpenError](https://fdc3.finos.org/docs/api/ref/Errors#openerror) enumeration.

Notably fd3-electron also has the same issue.

**Comment by kriswest** [comment]
Thanks @ColinEberhardt this was fixed in Finsemble 7.3.0 which throws an Error object including a stack trace.

FYI @mhmcclung
